"""Regenerate online_db/challenge02_tasks.py from the challenge-02 day files.

Single source of truth: activities/challenge-02-gamer-health/days/day-*.md
Run from the repository root:

    py -m scripts.build_challenge02_tasks
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence

from online_db.challenge02_days import load_challenge02_days

DEFAULT_DAYS_DIR = Path("activities/challenge-02-gamer-health/days")
DEFAULT_OUTPUT = Path("online_db/challenge02_tasks.py")

HEADER = '''"""Frozen challenge-02 activity content.

GENERATED by `py -m scripts.build_challenge02_tasks` -- do not edit by hand.
Source of truth: activities/challenge-02-gamer-health/days/day-*.md
"""
from __future__ import annotations

'''

METADATA = {
    "CHALLENGE02_SLUG": "challenge-gamer-health-7d",
    "CHALLENGE02_TITLE": "7 天教 AI 学会游戏人群健康管理",
    "CHALLENGE02_DESCRIPTION": (
        "用 7 天把游戏人群的健康管理教给 AI 学生（典型游戏宅人设）："
        "从健康账本与工位改造，到颈肩腕急救、吃、睡、练，"
        "最后一天综合验收，按标准区间 rubric 给老师出的健康计划打分。"
        "无打卡、碎片化参与，断签不算失败。"
    ),
    "CHALLENGE02_TOTAL_DAYS": 7,
    "CHALLENGE02_SESSION_TEMPLATE_ID": "challenge-gamer-health-7d-v1",
}


def render_module(days_dir: Path) -> str:
    days = load_challenge02_days(days_dir)
    if len(days) != METADATA["CHALLENGE02_TOTAL_DAYS"]:
        raise ValueError(
            f"expected {METADATA['CHALLENGE02_TOTAL_DAYS']} days, got {len(days)}"
        )
    lines = [HEADER]
    for key, value in METADATA.items():
        lines.append(f"{key} = {value!r}\n")
    lines.append("\nCHALLENGE02_TASKS = (\n")
    for day in days:
        lines.append("    {\n")
        lines.append(f"        \"day_number\": {day.day_number},\n")
        lines.append(f"        \"title\": {day.title!r},\n")
        lines.append(f"        \"task_markdown\": {day.task_markdown!r},\n")
        lines.append(f"        \"stage_goal\": {day.stage_goal!r},\n")
        lines.append(f"        \"module\": {day.module!r},\n")
        lines.append("    },\n")
    lines.append(")\n")
    return "".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--days-dir", type=Path, default=DEFAULT_DAYS_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="only verify the frozen module is in sync, do not write",
    )
    args = parser.parse_args(argv)

    rendered = render_module(args.days_dir)
    if args.check:
        current = args.output.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{args.output} is out of sync with {args.days_dir}")
            return 1
        print(f"{args.output} is in sync")
        return 0
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {args.output} from {args.days_dir}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
