"""Regenerate online_db/challenge01_tasks.py from the challenge-01 day files.

Single source of truth: activities/challenge-01-agent-app-dev/days/day-*.md
Run from the repository root:

    py -m scripts.build_challenge01_tasks
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence

from online_db.challenge01_days import load_challenge01_days

DEFAULT_DAYS_DIR = Path("activities/challenge-01-agent-app-dev/days")
DEFAULT_OUTPUT = Path("online_db/challenge01_tasks.py")

HEADER = '''"""Frozen challenge-01 activity content.

GENERATED by `py -m scripts.build_challenge01_tasks` -- do not edit by hand.
Source of truth: activities/challenge-01-agent-app-dev/days/day-*.md
"""
from __future__ import annotations

'''

METADATA = {
    "CHALLENGE01_SLUG": "challenge-agent-app-dev-17d",
    "CHALLENGE01_TITLE": "17 天教 AI 学会落地 agent 应用",
    "CHALLENGE01_DESCRIPTION": (
        "用 17 天把「如何从零落地一个 agent 应用」完整教给 AI 学生："
        "前两天亲手做四个对照实验，之后七个模块每天一讲一练，"
        "最后一天综合验收。累计制打卡，断签不算失败。"
    ),
    "CHALLENGE01_TOTAL_DAYS": 17,
    "CHALLENGE01_SESSION_TEMPLATE_ID": "challenge-agent-app-dev-17d-v1",
}


def render_module(days_dir: Path) -> str:
    days = load_challenge01_days(days_dir)
    if len(days) != METADATA["CHALLENGE01_TOTAL_DAYS"]:
        raise ValueError(
            f"expected {METADATA['CHALLENGE01_TOTAL_DAYS']} days, got {len(days)}"
        )
    lines = [HEADER]
    for key, value in METADATA.items():
        lines.append(f"{key} = {value!r}\n")
    lines.append("\nCHALLENGE01_TASKS = (\n")
    for day in days:
        lines.append("    {\n")
        lines.append(f"        \"day_number\": {day.day_number},\n")
        lines.append(f"        \"title\": {day.title!r},\n")
        lines.append(f"        \"task_markdown\": {day.task_markdown!r},\n")
        lines.append(f"        \"stage_goal\": {day.stage_goal!r},\n")
        lines.append("    },\n")
    lines.append(")\n")
    return "".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--days-dir", type=Path, default=DEFAULT_DAYS_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="only verify the frozen module is in sync, do not write",
    )
    args = parser.parse_args(argv)

    rendered = render_module(args.days_dir)
    if args.check:
        current = args.output.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{args.output} is out of sync with {args.days_dir}")
            return 1
        print(f"{args.output} is in sync")
        return 0
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {args.output} from {args.days_dir}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
